[package]
name = "stm32f746-hal"
version = "0.1.0"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]

[dependencies]
cortex-m = "0.4.3"
embedded-hal = "0.1.2"

[dependencies.stm32f7]
version = "0.1.0"
features = ["stm32f7x6"]
